version: '3.8'

services:
  hivision_idphotos:
    build:
      context: .
      dockerfile: Dockerfile
    image: hivision_idphotos
    command: python3 deploy_api.py
    ports:
      - "8080:8080"
    volumes:
      - ./images:/app/images

volumes:
  images:
