name: Sync to Gitee

on:
  push:
    branches:
      - master  # 或者你想要同步的其他分支

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to Gitee
      run: |
        git config --global user.name ${{ secrets.GITEE_USERNAME }}
        git config --global user.email ${{ secrets.GITEE_EMAIL }}
        git remote add gitee https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/${{ secrets.GITEE_USERNAME }}/HivisionIDPhotos.git
        git push -f gitee master:master
